// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6MzJICKwPgAkWLjwRkZs4EyxvKagg8o',
    appId: '1:113528284500:web:45464b5c0deb07d8a114c1',
    messagingSenderId: '113528284500',
    projectId: 'fruity-5ca4d',
    authDomain: 'fruity-5ca4d.firebaseapp.com',
    storageBucket: 'fruity-5ca4d.appspot.com',
    measurementId: 'G-0QVLQ7GFRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKOzpPdVjitM9FN0sxE2u4JuTs2MeGo4',
    appId: '1:113528284500:android:5be42157f9608fffa114c1',
    messagingSenderId: '113528284500',
    projectId: 'fruity-5ca4d',
    storageBucket: 'fruity-5ca4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2wdv67fWF8sYcTyXMiD3hLCrxbrIs59I',
    appId: '1:113528284500:ios:a88a468d72b0ecc8a114c1',
    messagingSenderId: '113528284500',
    projectId: 'fruity-5ca4d',
    storageBucket: 'fruity-5ca4d.appspot.com',
    iosClientId: '113528284500-k56uub5r8cma35nc5u5q67k1np34nrm4.apps.googleusercontent.com',
    iosBundleId: 'br.com.matterra.fruity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2wdv67fWF8sYcTyXMiD3hLCrxbrIs59I',
    appId: '1:113528284500:ios:a88a468d72b0ecc8a114c1',
    messagingSenderId: '113528284500',
    projectId: 'fruity-5ca4d',
    storageBucket: 'fruity-5ca4d.appspot.com',
    iosClientId: '113528284500-k56uub5r8cma35nc5u5q67k1np34nrm4.apps.googleusercontent.com',
    iosBundleId: 'br.com.matterra.fruity',
  );
}
